### ISSUE TITLE
Error: Cannot open registry file

### ISSUE THREAD

**Issue by ringtailedfox** [SynchronetBBS/sbbs#3]
I tried upgrading from version 3.16 to 3.19 and now SBBS's control panel program says it can't start because it can't open a registry file located at "\software\swindell\Synchronet Control Panel"... is that a registry entry and not a key? I tried uninstalling it and installing a fresh copy of 3.19 but this still remains.  I then tried to go back to 3.16, but this issue *still* remains.  what's going on?

**Comment by rswindell** [comment]
#1 this is the wrong place to ask support questions. See https://wiki.synchro.net/howto:support for details.

#2 I've never heard anyone encountering the issue you described. My guess is that you've install or run Synchronet as different users and thus the registry key cannot be accessed by the user you're running Synchronet as. Running regedit.exe (as Administrator if you have to) and deleting the specified registry key should resolve the problem.

**Comment by ringtailedfox** [comment]
ohhhh... alright.

i also figured out that if i ran the control panel as admin, it would load up normally... sorry to bother ya.

**Comment by rswindell** [comment]
Perhaps Synchronet was installed (and thus the Synchronet control panel was run for the first time and thus the Registry key created) as admin in the first place.
